import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import SideBar from '@/components/SideBar'
import SideBar2 from '@/components/SideBar2'
import NavBar from '@/components/NavBar'
// import styles from '@/styles/Home.module.scss'
const styles = {}

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/static/css/style.css" rel="stylesheet" />
        <link href="/static/vendor/jquery-nice-select/css/nice-select.css" rel="stylesheet" />
	      <link rel="stylesheet" href="/static/vendor/nouislider/nouislider.min.css" />
        <script src="/static/vendor/global/global.min.js"></script>
        <script src="/static/vendor/chart.js/Chart.bundle.min.js"></script>
        <script src="static/vendor/jquery-nice-select/js/jquery.nice-select.min.js"></script>

        <script defer src="/static/vendor/nouislider/nouislider.min.js"></script>
        <script defer src="/static/vendor/wnumb/wNumb.js"></script>
        
        {/* <script src="/static/vendor/apexchart/apexchart.js"></script> */}
        {/* <script src="/static/js/dashboard/dashboard-1.js"></script> */}

        <script defer src="/static/js/custom.min.js"></script>
        <script defer src="/static/js/dlabnav-init.js"></script>
        <script defer src="/static/js/demo.js"></script>
        <script defer src="/static/js/styleSwitcher.js"></script>
      </Head>
      
      <main id="main-wrapper">
       <NavBar />
        <SideBar />
       <SideBar2 />
      </main>
    </>
  )
}
